# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotalRouter < Formula
  desc "Notal router executor"
  homepage "https://notal.io"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neidigital/notal/releases/download/v0.0.4/notal-router_0.0.4_darwin_amd64.tar.gz"
      sha256 "e50869fdf5f5edbfde0b1aa39a9cf2f58f8d6a1a92a1323b5c1bb9dd9a1c8adc"

      define_method(:install) do
        bin.install "notal-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neidigital/notal/releases/download/v0.0.4/notal-router_0.0.4_darwin_arm64.tar.gz"
      sha256 "a2ae6bd0f5a07e6d1096c2a6d2e9aa0ae201e6b98086336f98c9c44a69c5244d"

      define_method(:install) do
        bin.install "notal-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neidigital/notal/releases/download/v0.0.4/notal-router_0.0.4_linux_amd64.tar.gz"
      sha256 "ba03837feb1d0934cfa040112579ad73530809a2b7704571da25d2db70a6cd31"
      define_method(:install) do
        bin.install "notal-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neidigital/notal/releases/download/v0.0.4/notal-router_0.0.4_linux_arm64.tar.gz"
      sha256 "3c54a882abdfb9b6cb103ebdab7c0b748c91b00adf7a89afa11d3a6bc70185e1"
      define_method(:install) do
        bin.install "notal-router"
      end
    end
  end

  test do
    system "#{bin}/notal-router", "--version"
  end
end
