# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NotalRouter < Formula
  desc "Notal router executor"
  homepage "https://notal.io"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neidigital/notal/releases/download/v0.0.3/notal-router_0.0.3_darwin_amd64.tar.gz"
      sha256 "32af3e24f3d2feb35f68ac948ea8930999fee74f9c074ccf43d8ebffae2945d5"

      define_method(:install) do
        bin.install "notal-router"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neidigital/notal/releases/download/v0.0.3/notal-router_0.0.3_darwin_arm64.tar.gz"
      sha256 "0dc364721c7fc4fd42d2ac4380dfde3ea90f185204ca0fa48068da1b75b0148a"

      define_method(:install) do
        bin.install "notal-router"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neidigital/notal/releases/download/v0.0.3/notal-router_0.0.3_linux_amd64.tar.gz"
      sha256 "9a7f33709e4eb4eacd15349d8b6fce344c3858a646613528c311b344f0b12182"
      define_method(:install) do
        bin.install "notal-router"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neidigital/notal/releases/download/v0.0.3/notal-router_0.0.3_linux_arm64.tar.gz"
      sha256 "143537c1e83b5bc7ad963a52ef58a85a6ba4896713f134a77a2ac4a90973225c"
      define_method(:install) do
        bin.install "notal-router"
      end
    end
  end

  test do
    system "#{bin}/notal-router", "--version"
  end
end
